name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - feature/testing

jobs:
  cambios_a_testing:
    runs-on: ubuntu-latest
    steps:
      - name: actualizando repo
        run: echo "repositorio actualizado"
