name: Deploy to GitHub Pages

event: push
  branch: feature/testing

job:
  name: cambios a testing
    runs-on: ubuntu/latest
    steps:
      - name: actualizando repo
        run: echo "repositorio actualizado"
