name: Deploy a GitHub Pages

# Evento que activa el workflow
on:
  push: # Cuando subas cambios
    branches:
      - feature/testing # Solo para la feature/testing

permissions: # Establece permisos para el token
  id-token: write
  contents: read

# Job para el despliegue
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias (si usas Node.js o similares)
      run: npm install # O el comando que necesites si usas npm/yarn
    
    - name: Compilar los archivos estáticos
      run: npm run build # Asegúrate de tener este comando para generar los archivos estáticos

    - name: Subir artefacto para despliegue
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./dist # Cambia este path por el directorio donde se encuentran tus archivos estáticos        
    
    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v3

    - name: Desplegar en GitHub Pages
      uses: actions/deploy-pages@v1
